### ISSUE TITLE
Overall - presentatie nieuwe design Donderdag 19 mei

### ISSUE THREAD

**Issue by rschoemaker12** [codeGorillaNL/CodeMatch#12]
presentatie voorbereiden.

**Comment by ramon-webdevpro-nl** [comment]
Robin,

De presentatie wordt gegeven door Harco en Bjorn, niet door mij.

Ramon

**Comment by rschoemaker12** [comment]
Is aangepast dank je wel
robin
----Origineel Bericht----
Van : notifications@github.com
Datum : 17/05/2017 11:22
Aan : CodeMatch@noreply.github.com
Cc : r.schoemaker@codegorilla.nl, author@noreply.github.com
Onderwerp : Re: [codeGorillaNL/CodeMatch] presentatie nieuwe design Donderdeag 19 mei (#12)
Robin,
 De presentatie wordt gegeven door Harco en Bjorn, niet door mij.
 Ramon
